name: pymeria
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pillow
  - click
  - requests
  - pymomentum>=0.1.15
  - tqdm
  - pip
  - pip:
    - loguru
    - projectaria-tools==1.5.5
    - -e .
